version: '3'
services:
    db:
      image: postgres:latest
      environment:
        POSTGRES_USER: root
        POSTGRES_PASSWORD: password
        TZ: "Asia/Tokyo"
      ports:
        - 5432:5432
      volumes:
        - ./tmp/postgres:/var/lib/postgresql/data
