# SQLite. Versions 3.8.0 and up are supported.
#   gem install sqlite3
#
#   Ensure the SQLite 3 gem is defined in your Gemfile
#   gem 'sqlite3'
#
default: &default
  adapter: mysql2
  encoding: utf8
  pool: <%= ENV.fetch("RAILS_MAX_THREADS") { 5 } %>
  timeout: 5000

development:
  <<: *default
  database: vimate_development
  username: root
  host: <%= Rails.application.credentials.db[:host] %>
  password: <%= Rails.application.credentials.db[:password] %>

test:
  <<: *default
  database: vimate_test
  username: root
  host: <%= Rails.application.credentials.db[:host] %>
  password: <%= Rails.application.credentials.db[:password] %>

production:
  <<: *default
  database: vimate_production
  username: admin
  host: <%= Rails.application.credentials.db[:host] %>
  password: <%= Rails.application.credentials.db[:password] %>
