# SQLite. Versions 3.8.0 and up are supported.
#   gem install sqlite3
#
#   Ensure the SQLite 3 gem is defined in your Gemfile
#   gem 'sqlite3'
#
default: &default
  adapter: mysql2
  encoding: utf8
  pool: <%= ENV.fetch("RAILS_MAX_THREADS") { 5 } %>
  username: root
  password: <%= ENV['DATABASE_PASSWORD'] %>
  host: localhost
  timeout: 5000

development:
  <<: *default
  database: vimate_development

test:
  <<: *default
  database: vimate_test

production:
  <<: *default
  database: vimate_production
  username: admin
  host: <%= ENV['DATABASE_HOST'] %>
