# SQLite. Versions 3.8.0 and up are supported.
#   gem install sqlite3
#
#   Ensure the SQLite 3 gem is defined in your Gemfile
#   gem 'sqlite3'
#
default: &default
  adapter: postgresql
  encoding: utf8
  pool: <%= ENV.fetch("RAILS_MAX_THREADS") { 5 } %>
  timeout: 5000

local: &local
  <<: *default
  host: <%= Rails.application.credentials.db[:host] %>
  password: <%= Rails.application.credentials.db[:password] %>

development:
  <<: *local
  database: vimate_development
  username: root

test:
  <<: *local
  database: vimate_test
  username: root

production:
  <<: *default
  # database: vimate_production
  # username: admin
  url: <%= ENV['DATABASE_URL'] %>
